# Generated by Django 4.2.30 on 2026-06-19 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='e.g. bottles, mugs, diaries, pens', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('features', models.JSONField(blank=True, default=list)),
                ('offer', models.TextField(blank=True, null=True)),
                ('sizes', models.JSONField(blank=True, default=list)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('customizations', models.JSONField(blank=True, default=list)),
                ('quantities', models.JSONField(blank=True, default=list)),
                ('price_per_item', models.JSONField(blank=True, default=dict)),
                ('images', models.JSONField(blank=True, default=list)),
                ('print_zones', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='BulkInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254)),
                ('items', models.JSONField(default=list, help_text='List of items in the cart with their custom logo, color, size, etc.')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_items', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
