# Generated by Django 4.2.30 on 2026-06-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contactmessage_couponcode_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='print_zones',
        ),
        migrations.AddField(
            model_name='product',
            name='max_logo_size',
            field=models.PositiveIntegerField(default=150, help_text='Maximum allowed logo dimension in pixels'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_text_length',
            field=models.PositiveIntegerField(default=50, help_text='Maximum characters allowed in custom text fields'),
        ),
        migrations.AddField(
            model_name='product',
            name='rotation_enabled',
            field=models.BooleanField(default=True, help_text='Enable rotation controls in customization editor'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_margins_enabled',
            field=models.BooleanField(default=True, help_text='Turn border red and show warnings if design exceeds printable zone'),
        ),
        migrations.AddField(
            model_name='product',
            name='snap_guides_enabled',
            field=models.BooleanField(default=True, help_text='Enable vertical and horizontal guide lines'),
        ),
        migrations.CreateModel(
            name='PrintZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(help_text='e.g. front_logo, lid_engraving, cover', max_length=50)),
                ('title', models.CharField(help_text='Display title, e.g. Main Body Print', max_length=100)),
                ('zone_type', models.CharField(default='flat', help_text='flat or cylindrical', max_length=50)),
                ('px', models.FloatField(help_text='X position ratio (0.0 to 1.0) on template canvas')),
                ('py', models.FloatField(help_text='Y position ratio (0.0 to 1.0) on template canvas')),
                ('pWidth', models.FloatField(help_text='Width ratio (0.0 to 1.0) relative to template width')),
                ('pHeight', models.FloatField(help_text='Height ratio (0.0 to 1.0) relative to template height')),
                ('angle', models.FloatField(default=0, help_text='Default print zone angle in degrees')),
                ('shape', models.CharField(default='rectangle', help_text='rectangle or circle', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_zones_rel', to='accounts.product')),
            ],
        ),
    ]
