# Generated by Django 4.2.30 on 2026-06-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_product_print_zones_product_max_logo_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_logo_size',
            field=models.PositiveIntegerField(default=120, help_text='Default logo width in pixels upon placement'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_text_size',
            field=models.PositiveIntegerField(default=24, help_text='Default font size for added text'),
        ),
        migrations.AddField(
            model_name='product',
            name='logo_customization_enabled',
            field=models.BooleanField(default=True, help_text='Allow logo uploads'),
        ),
        migrations.AddField(
            model_name='product',
            name='text_customization_enabled',
            field=models.BooleanField(default=True, help_text='Allow text customization'),
        ),
    ]
