# Generated by Django 6.0.6 on 2026-06-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_product_default_logo_size_product_default_text_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(default='hariom@upi', help_text='UPI ID for payment', max_length=100)),
                ('qr_code', models.FileField(blank=True, help_text='QR Code image for UPI payment', null=True, upload_to='payment/')),
                ('bank_name', models.CharField(default='State Bank of India', help_text='Bank Name', max_length=100)),
                ('account_name', models.CharField(default='Hari Om Print House', help_text='Account Name', max_length=150)),
                ('account_number', models.CharField(default='1234567890', help_text='Bank Account Number', max_length=50)),
                ('ifsc_code', models.CharField(default='SBIN0001234', help_text='IFSC Code', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bulkinquiry',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bulkinquiry',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bulkinquiry',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkinquiry',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bulkinquiry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkinquiry',
            name='payment_method',
            field=models.CharField(blank=True, help_text='e.g. UPI, BANK_TRANSFER', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulkinquiry',
            name='payment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkinquiry',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='bulkinquiry',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkinquiry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bulkinquiry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('PROCESSING', 'Processing'), ('PRINTING', 'Printing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
