# Generated by Django 5.2.15 on 2026-06-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bulkinquiry_admin_remarks_bulkinquiry_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkinquiry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Inquiry)'), ('APPROVED', 'Approved (Awaiting Payment)'), ('REJECTED', 'Rejected'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('PAYMENT_VERIFIED', 'Payment Verified / Confirmed'), ('PROCESSING', 'Processing'), ('PRINTING', 'Printing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
