# Generated by Django 6.0.6 on 2026-07-01 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_bulkinquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(help_text='e.g. bottles, mugs, diaries, pens', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Is this the default product shown for this category on the website?'),
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(help_text='e.g. #ffffff', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/colors/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='accounts.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='accounts.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Minimum quantity for this price, e.g. 50')),
                ('price_per_item', models.DecimalField(decimal_places=2, help_text='Price per item at this tier', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='accounts.product')),
            ],
            options={
                'ordering': ['quantity'],
                'unique_together': {('product', 'quantity')},
            },
        ),
    ]
